In [7]:
import torch

if torch.cuda.is_available():
    print("GPU is available:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected.")


No GPU detected.


In [8]:
tensor_a = torch.rand(3,3)
tensor_b = torch.rand(3,3)

result = torch.matmul(tensor_a, tensor_b)

# print the result

print(f"Tensor A:\n{tensor_a}\nTensor B:\n{tensor_b}\nResult of matrix multiplication:\n{result}")

Tensor A:
tensor([[0.8389, 0.0858, 0.1024],
        [0.9856, 0.4908, 0.7084],
        [0.1624, 0.4802, 0.3094]])
Tensor B:
tensor([[0.6146, 0.1825, 0.8298],
        [0.2952, 0.8316, 0.2268],
        [0.6510, 0.1778, 0.2691]])
Result of matrix multiplication:
tensor([[0.6076, 0.2427, 0.7431],
        [1.2118, 0.7140, 1.1198],
        [0.4430, 0.4840, 0.3270]])


No GPU detected.
