In [48]:
import numpy as np

In [49]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


### Built in methods

In [50]:
zeroes = np.zeros((3,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
ones = np.ones((2,4))
ones


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### arange(): similar to range

In [52]:
range_array = np.arange(1,10,2)
print(range_array)

[1 3 5 7 9]


#### linspace(): evenly spaced numbers

In [53]:
linspace_array = np.linspace(0,10,3)
linspace_array

array([ 0.,  5., 10.])

In [54]:
arr = np.array([1,2,3,4,5,6])



In [55]:
reshaped = arr.reshape((2,3))

In [56]:
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
reshaped = arr.reshape((3,2))

In [58]:
reshaped


array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
arr = np.array([1,2,3])


In [60]:
expanded = arr[: , np.newaxis]

In [61]:
print(expanded)

[[1]
 [2]
 [3]]


#### Basic Operations


In [62]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [63]:
a + b

array([5, 7, 9])

In [64]:
a*b

array([ 4, 10, 18])

In [65]:
a/b

array([0.25, 0.4 , 0.5 ])

In [66]:
arr = np.array([4,16,25])
np.sqrt(arr)

array([2., 4., 5.])

In [67]:
np.sum(arr)

45

In [68]:
np.mean(arr)

15.0

In [69]:
np.max(arr)

25

In [70]:
np.min(arr)

4

In [71]:
arr = np.array([10,20,30,40,50])

print(arr[2])

30


In [72]:
print(arr[-1])

50


In [73]:
arr[1:4]

array([20, 30, 40])

In [74]:
arr[:]

array([10, 20, 30, 40, 50])

In [75]:
arr

array([10, 20, 30, 40, 50])

In [76]:
reshaped = arr.reshape((5,1))

In [77]:
reshaped

array([[10],
       [20],
       [30],
       [40],
       [50]])

qns

In [78]:
a = np.arange(1,6)
b = np.arange(6,11)

In [79]:
listted = [f"Add: {a+b}",
           f"Sub: {a-b}",
           f"Mul: {a*b}",
           f"Div: {a/b}"
           ]

In [88]:
print('\n'.join(i for i in listted))

Add: [ 7  9 11 13 15]
Sub: [-5 -5 -5 -5 -5]
Mul: [ 6 14 24 36 50]
Div: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [89]:
# QN

In [90]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [91]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
# transpose

In [93]:
transpose = matrix.T

In [94]:
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
another_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])

#### Broadcasting

In [99]:
arr = np.array([1,2,3])
arr + 10

array([11, 12, 13])

In [101]:
matrix = np.array([[1,2,3],[4,5,6]])
vector = np.array([1,0,1])

In [102]:
matrix + vector

array([[2, 2, 4],
       [5, 5, 7]])

#### Aggregation

In [103]:
arr = np.array([[1,2,3], [4,5,6]])


In [104]:
np.sum(arr)

21

In [105]:
np.mean(arr)

3.5

In [107]:
arr.mean()

3.5

In [120]:
import time

begin = time.thread_time_ns()

np.std(arr)

print(begin)

10640625000


In [121]:

begin = time.thread_time_ns()
arr.std()
print(begin)

10671875000


In [122]:
# Sumof rows

np.sum(arr, axis=1)

array([ 6, 15])

In [123]:
np.sum(arr, axis=0)

array([5, 7, 9])

#### Boolean Indexing and Filtering

In [124]:
arr = np.array([1,2,3,4,5,6])

In [125]:
evens = arr[arr%2==0]

In [126]:
evens

array([2, 4, 6])

In [127]:
arr[arr>3]=0

In [128]:
arr

array([1, 2, 3, 0, 0, 0])

#### Random Numbers

In [133]:
np.random.seed(42)

In [134]:
random_array = np.random.rand(3,3)

In [135]:
random_array

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [136]:
random_integers = np.random.randint(0,10,size=(2,3))

In [137]:
random_integers

array([[7, 2, 5],
       [4, 1, 7]])

In [138]:
dataset = np.random.randint(1,51,size=(5,5))

In [139]:
dataset

array([[44, 30, 38,  2, 21],
       [33, 12, 22, 44, 25],
       [49, 27, 42, 28, 16],
       [15, 47, 44,  3, 37],
       [ 7, 21,  9, 39, 18]])

filter value > 25 and replace with 0

In [140]:
dataset[dataset>25]=0

In [142]:
dataset.sum()


171

In [143]:
dataset.mean()

6.84

In [145]:
dataset.std()

8.748394138354763